"""
Precision Autoimmune Agent — Export Module

Generates clinical reports in multiple formats:
- Markdown (structured text)
- PDF (styled clinical report)
- FHIR R4 DiagnosticReport bundle (JSON)

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

import json
import io
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pathlib import Path

from loguru import logger


class AutoimmuneExporter:
    """Export autoimmune analysis results in multiple formats."""

    def __init__(self, knowledge_version: Optional[Dict] = None):
        self.knowledge_version = knowledge_version or {}
        self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── Markdown Export ────────────────────────────────────────────────

    def to_markdown(
        self,
        patient_id: str,
        analysis_result: Any = None,
        query_answer: Optional[str] = None,
        evidence_hits: Optional[List[Dict]] = None,
    ) -> str:
        """Generate a Markdown clinical report."""
        lines = [
            "# Precision Autoimmune Intelligence Report",
            "",
            f"**Patient ID:** {patient_id}",
            f"**Generated:** {self.generated_at}",
            f"**Knowledge Base:** v{self.knowledge_version.get('version', '?')}",
            "",
            "---",
            "",
        ]

        if analysis_result:
            lines.extend(self._format_analysis_md(analysis_result))

        if query_answer:
            lines.extend([
                "## Clinical Query Response",
                "",
                query_answer,
                "",
            ])

        if evidence_hits:
            lines.extend(self._format_evidence_md(evidence_hits))

        lines.extend([
            "---",
            "",
            "*This report was generated by the Precision Autoimmune Intelligence Agent, "
            "part of the HCLS AI Factory on NVIDIA DGX Spark. "
            "All findings require clinical validation.*",
            "",
            f"*Knowledge Base Version: {self.knowledge_version.get('version', 'N/A')} | "
            f"Last Updated: {self.knowledge_version.get('last_updated', 'N/A')}*",
        ])

        return "\n".join(lines)

    def _format_analysis_md(self, result) -> List[str]:
        """Format AutoimmuneAnalysisResult as Markdown sections."""
        lines = []

        # Critical alerts
        alerts = getattr(result, "critical_alerts", [])
        if alerts:
            lines.extend(["## Critical Alerts", ""])
            for alert in alerts:
                lines.append(f"- **⚠️ {alert}**")
            lines.append("")

        # Disease activity scores
        scores = getattr(result, "disease_activity_scores", [])
        if scores:
            lines.extend(["## Disease Activity Scores", ""])
            lines.append("| Score | Value | Level | Disease |")
            lines.append("|-------|-------|-------|---------|")
            for s in scores:
                disease = s.disease.value.replace("_", " ").title() if hasattr(s.disease, "value") else str(s.disease)
                level = s.level.value.upper() if hasattr(s.level, "value") else str(s.level)
                lines.append(f"| {s.score_name} | {s.score_value} | {level} | {disease} |")
            lines.append("")

        # Flare predictions
        preds = getattr(result, "flare_predictions", [])
        if preds:
            lines.extend(["## Flare Risk Predictions", ""])
            for p in preds:
                disease = p.disease.value.replace("_", " ").title() if hasattr(p.disease, "value") else str(p.disease)
                risk = p.predicted_risk.value.upper() if hasattr(p.predicted_risk, "value") else str(p.predicted_risk)
                lines.append(f"### {disease} — Risk: **{risk}** (score: {p.risk_score:.2f})")
                if p.contributing_factors:
                    lines.append("\n**Contributing Factors:**")
                    for f in p.contributing_factors:
                        lines.append(f"- {f}")
                if p.protective_factors:
                    lines.append("\n**Protective Factors:**")
                    for f in p.protective_factors:
                        lines.append(f"- {f}")
                if p.recommended_monitoring:
                    lines.append("\n**Recommended Monitoring:**")
                    for m in p.recommended_monitoring:
                        lines.append(f"- {m}")
                lines.append("")

        # HLA associations
        hla = getattr(result, "hla_associations", [])
        if hla:
            lines.extend(["## HLA-Disease Associations", ""])
            lines.append("| Allele | Disease | Odds Ratio | PMID |")
            lines.append("|--------|---------|-----------|------|")
            for a in hla:
                disease = a.get("disease", "").replace("_", " ").title()
                lines.append(f"| {a.get('allele', '')} | {disease} | {a.get('odds_ratio', '')} | {a.get('pmid', '')} |")
            lines.append("")

        # Biologic recommendations
        biologics = getattr(result, "biologic_recommendations", [])
        if biologics:
            lines.extend(["## Biologic Therapy Recommendations", ""])
            for t in biologics:
                lines.append(f"### {t.drug_name} ({t.drug_class})")
                lines.append(f"**Mechanism:** {t.mechanism}")
                if t.pgx_considerations:
                    lines.append("\n**PGx Considerations:**")
                    for pgx in t.pgx_considerations:
                        lines.append(f"- {pgx}")
                if t.contraindications:
                    lines.append("\n**Contraindications:**")
                    for ci in t.contraindications:
                        lines.append(f"- {ci}")
                if t.monitoring_requirements:
                    lines.append("\n**Monitoring Requirements:**")
                    for m in t.monitoring_requirements:
                        lines.append(f"- {m}")
                lines.append("")

        return lines

    def _format_evidence_md(self, hits: List[Dict]) -> List[str]:
        """Format evidence hits as Markdown."""
        lines = ["## Evidence Sources", ""]
        for i, hit in enumerate(hits[:15], 1):
            collection = hit.get("collection", "unknown")
            score = hit.get("score", 0)
            text = hit.get("text", "")[:300]
            relevance = hit.get("relevance", "low")
            badge = {"high": "🟢", "medium": "🟡", "low": "🔴"}.get(relevance, "⚪")
            lines.append(f"**{i}. {badge} [{collection}]** (score: {score:.3f})")
            lines.append(f"> {text}")
            lines.append("")
        return lines

    # ── PDF Export ─────────────────────────────────────────────────────

    def to_pdf_bytes(
        self,
        patient_id: str,
        analysis_result: Any = None,
        query_answer: Optional[str] = None,
        evidence_hits: Optional[List[Dict]] = None,
    ) -> bytes:
        """Generate a styled PDF report. Returns bytes for download."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.colors import HexColor
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.units import inch
        except ImportError:
            # Fallback: return markdown as plain text PDF-like bytes
            logger.warning("reportlab not installed — returning Markdown as fallback")
            md = self.to_markdown(patient_id, analysis_result, query_answer, evidence_hits)
            return md.encode("utf-8")

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)

        styles = getSampleStyleSheet()
        nvidia_green = HexColor("#76B900")

        title_style = ParagraphStyle(
            "CustomTitle", parent=styles["Title"],
            textColor=nvidia_green, fontSize=18, spaceAfter=12,
        )
        heading_style = ParagraphStyle(
            "CustomHeading", parent=styles["Heading2"],
            textColor=nvidia_green, fontSize=14, spaceAfter=8,
        )
        body_style = styles["BodyText"]
        alert_style = ParagraphStyle(
            "Alert", parent=body_style,
            textColor=HexColor("#FF4444"), fontSize=11, spaceAfter=4,
        )

        elements = []

        # Title
        elements.append(Paragraph("Precision Autoimmune Intelligence Report", title_style))
        elements.append(Paragraph(f"Patient ID: {patient_id} | Generated: {self.generated_at}", body_style))
        elements.append(Spacer(1, 12))

        if analysis_result:
            # Critical alerts
            alerts = getattr(analysis_result, "critical_alerts", [])
            if alerts:
                elements.append(Paragraph("Critical Alerts", heading_style))
                for alert in alerts:
                    elements.append(Paragraph(f"⚠ {alert}", alert_style))
                elements.append(Spacer(1, 8))

            # Disease activity scores table
            scores = getattr(analysis_result, "disease_activity_scores", [])
            if scores:
                elements.append(Paragraph("Disease Activity Scores", heading_style))
                table_data = [["Score", "Value", "Level", "Disease"]]
                for s in scores:
                    disease = s.disease.value.replace("_", " ").title() if hasattr(s.disease, "value") else str(s.disease)
                    level = s.level.value.upper() if hasattr(s.level, "value") else str(s.level)
                    table_data.append([s.score_name, str(s.score_value), level, disease])
                t = Table(table_data, colWidths=[1.5 * inch, 1 * inch, 1.2 * inch, 2.5 * inch])
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), nvidia_green),
                    ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CCCCCC")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F8F8F8"), HexColor("#FFFFFF")]),
                ]))
                elements.append(t)
                elements.append(Spacer(1, 12))

            # Biologic recommendations
            biologics = getattr(analysis_result, "biologic_recommendations", [])
            if biologics:
                elements.append(Paragraph("Biologic Therapy Recommendations", heading_style))
                for therapy in biologics:
                    elements.append(Paragraph(
                        f"<b>{therapy.drug_name}</b> ({therapy.drug_class}) — {therapy.mechanism}",
                        body_style,
                    ))
                    if therapy.pgx_considerations:
                        for pgx in therapy.pgx_considerations:
                            elements.append(Paragraph(f"  • PGx: {pgx}", body_style))
                    if therapy.monitoring_requirements:
                        for m in therapy.monitoring_requirements[:3]:
                            elements.append(Paragraph(f"  • Monitor: {m}", body_style))
                    elements.append(Spacer(1, 6))

        if query_answer:
            elements.append(Paragraph("Clinical Query Response", heading_style))
            # Split long text into paragraphs
            for para in query_answer.split("\n\n"):
                clean = para.replace("<", "&lt;").replace(">", "&gt;").strip()
                if clean:
                    elements.append(Paragraph(clean, body_style))
            elements.append(Spacer(1, 8))

        # Footer
        elements.append(Spacer(1, 24))
        footer_style = ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=HexColor("#888888"))
        elements.append(Paragraph(
            "Generated by Precision Autoimmune Intelligence Agent | HCLS AI Factory | NVIDIA DGX Spark | "
            "All findings require clinical validation.",
            footer_style,
        ))

        doc.build(elements)
        return buf.getvalue()

    # ── FHIR R4 Export ─────────────────────────────────────────────────

    def to_fhir_r4(
        self,
        patient_id: str,
        analysis_result: Any = None,
        query_answer: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Generate a FHIR R4 DiagnosticReport bundle."""
        now = datetime.now(timezone.utc).isoformat()

        bundle = {
            "resourceType": "Bundle",
            "type": "collection",
            "timestamp": now,
            "meta": {
                "profile": ["http://hl7.org/fhir/StructureDefinition/Bundle"],
                "source": "HCLS AI Factory - Precision Autoimmune Agent",
            },
            "entry": [],
        }

        # Patient resource
        bundle["entry"].append({
            "resource": {
                "resourceType": "Patient",
                "id": patient_id,
                "identifier": [{"system": "urn:hcls-ai-factory:patient", "value": patient_id}],
            },
        })

        # DiagnosticReport
        report = {
            "resourceType": "DiagnosticReport",
            "id": f"autoimmune-report-{patient_id}",
            "status": "final",
            "category": [{"coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0074", "code": "LAB", "display": "Laboratory"}]}],
            "code": {"coding": [{"system": "http://loinc.org", "code": "11502-2", "display": "Laboratory report"}], "text": "Autoimmune Disease Analysis"},
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": now,
            "issued": now,
            "conclusion": "",
            "result": [],
        }

        conclusions = []

        if analysis_result:
            # Disease activity observations
            for i, score in enumerate(getattr(analysis_result, "disease_activity_scores", [])):
                obs_id = f"activity-{i}"
                disease = score.disease.value if hasattr(score.disease, "value") else str(score.disease)
                level = score.level.value if hasattr(score.level, "value") else str(score.level)
                obs = {
                    "resourceType": "Observation",
                    "id": obs_id,
                    "status": "final",
                    "category": [{"coding": [{"system": "http://terminology.hl7.org/CodeSystem/observation-category", "code": "laboratory"}]}],
                    "code": {"text": f"{score.score_name} ({disease})"},
                    "valueQuantity": {"value": score.score_value, "unit": "score"},
                    "interpretation": [{"text": level}],
                    "subject": {"reference": f"Patient/{patient_id}"},
                }
                bundle["entry"].append({"resource": obs})
                report["result"].append({"reference": f"Observation/{obs_id}"})
                conclusions.append(f"{score.score_name}: {score.score_value} ({level})")

            # Flare risk observations
            for i, pred in enumerate(getattr(analysis_result, "flare_predictions", [])):
                obs_id = f"flare-risk-{i}"
                disease = pred.disease.value if hasattr(pred.disease, "value") else str(pred.disease)
                risk = pred.predicted_risk.value if hasattr(pred.predicted_risk, "value") else str(pred.predicted_risk)
                obs = {
                    "resourceType": "Observation",
                    "id": obs_id,
                    "status": "final",
                    "code": {"text": f"Flare Risk Prediction ({disease})"},
                    "valueQuantity": {"value": pred.risk_score, "unit": "probability"},
                    "interpretation": [{"text": risk}],
                    "subject": {"reference": f"Patient/{patient_id}"},
                }
                bundle["entry"].append({"resource": obs})
                report["result"].append({"reference": f"Observation/{obs_id}"})
                conclusions.append(f"Flare risk for {disease}: {risk} ({pred.risk_score:.2f})")

            # Critical alerts
            for alert in getattr(analysis_result, "critical_alerts", []):
                conclusions.append(f"ALERT: {alert}")

        if query_answer:
            conclusions.append(f"Clinical Query Response: {query_answer[:500]}")

        report["conclusion"] = " | ".join(conclusions) if conclusions else "Analysis complete. See observations."
        bundle["entry"].append({"resource": report})

        return bundle

    def to_fhir_json(self, patient_id: str, analysis_result: Any = None, query_answer: Optional[str] = None) -> str:
        """Return FHIR R4 bundle as formatted JSON string."""
        bundle = self.to_fhir_r4(patient_id, analysis_result, query_answer)
        return json.dumps(bundle, indent=2, default=str)
